EShop-Gp/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EShop_Gp.Models
{
    public class Cart
    {
        [Key]
        public int Id { get; set; }
        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        public Product Product { get; set; }
        public DateTime AddedTime { get; set; }
        public string UserId { get; set; }
        public int ItemsId { get; set; }
        public Items Items { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPaid { get; set; }
        public int CartMasterId { get; set; }
        [ForeignKey("CartMasterId")]
        public CartMaster CartMaster { get; set; }
    }
}

EShop-Gp/Controllers/CartController.cs
using EShop_Gp.Data;
using EShop_Gp.Models;
using EShop_Gp.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EShop_Gp.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _Context;

        public CartController(ApplicationDbContext Context)
        {
            _Context = Context;
        }
        public IActionResult Index()
        {
            var UserN = User.Identity.Name;
            var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN);
            if (UserId != null)
            {
                var viewmodel = new PopUp()
                {
                    carts = _Context.Cart.Where(x => x.UserId == UserId.Id && x.IsDeleted == false && x.IsPaid == false).Include(c => c.Product).Include(c => c.Items).Where(x => x.UserId == UserId.Id).ToList(),
                };
                viewmodel.SumPrice = viewmodel.carts.Select(s => s.Items.Price).Sum();
                if (viewmodel.carts != null && viewmodel.carts.Count() != 0)
                {
                    viewmodel.Items = _Context.Items.Where(x => x.ProductId == viewmodel.carts.FirstOrDefault().ProductId).Take(3).ToList();
                }

                return PartialView(viewmodel);
            }
            return View();
        }
        public ActionResult _Cart()
        {
            var UserN = User.Identity.Name;
            var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN);
            if (UserId != null)
            {
                var viewmodel = new PopUp()
                {
                    carts = _Context.Cart.Where(x => x.UserId == UserId.Id && x.IsDeleted == false && x.IsPaid == false).Include(c => c.Product).Include(c => c.Items).Where(x => x.UserId == UserId.Id).ToList(),
                };
                viewmodel.SumPrice = viewmodel.carts.Select(s => s.Items.Price).Sum();
                if (viewmodel.carts != null && viewmodel.carts.Count() != 0)
                {
                    viewmodel.Items = _Context.Items.Where(x => x.ProductId == viewmodel.carts.FirstOrDefault().ProductId).Take(3).ToList();
                }

                return PartialView(viewmodel);
            }
            else
            {
                return PartialView("_LoginToContinueCart");
            }
        }
        public ActionResult _LoginToContinueCart()
        {
            return View();
        }
        public ActionResult DeleteDiscarding(int Id)
        {
            var UserN = User.Identity.Name;
            var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN);
            if (UserId != null)
            {
                var Cart = _Context.Cart.FirstOrDefault(x => x.ItemsId == Id && x.UserId == UserId.Id && x.IsDeleted == false);
                Cart.IsDeleted = true;
                Cart.IsActive = false;
                _Context.Entry(Cart).CurrentValues.SetValues(Cart);

                _Context.SaveChanges();

                return RedirectToAction("_Cart");
            }
            else
            {
                return null;
            }
        }
        public ActionResult _StatusOrder()
        {
            var UserN = User.Identity.Name;
            if (UserN != null)
            {
                var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN).Id;
                if (UserId != null)
                {
                    List<StatusOrderViewModel> StatusOrderViewModelList = new List<StatusOrderViewModel>();

                    var CartMaster = _Context.CartMaster.FirstOrDefault(x => x.UserId == UserId);
                    if (CartMaster != null)
                    {
                        var Cart = _Context.Cart.Include(x => x.Items).Where(s => s.CartMasterId == CartMaster.Id);
                        foreach (var item in Cart)
                        {
                            StatusOrderViewModel StatusOrderViewModel = new StatusOrderViewModel();

                            StatusOrderViewModel.Image = item.Items.Image;
                            StatusOrderViewModel.ItemId = item.ItemsId;
                            StatusOrderViewModel.NameAr = item.Items.NameAr;
                            StatusOrderViewModel.NameEn = item.Items.NameEn;
                            StatusOrderViewModel.Price = item.Items.Price;
                            StatusOrderViewModel.OrderTimeOfReceipt = CartMaster.OrderTime.Value.AddDays(5).ToString("yyyy/MM/dd");
                            StatusOrderViewModelList.Add(StatusOrderViewModel);
                        }
                        return PartialView(StatusOrderViewModelList);
                    }
                    else
                    {
                        return PartialView();
                    }
                }
                else
                {
                    return PartialView("_LoginToContinueCart");
                }
            }
            else
            {
                return PartialView("_LoginToContinueCart");
            }
        }
    }
}

EShop-Gp/Controllers/PayedController.cs
using EShop_Gp.Data;
using EShop_Gp.Models;
using EShop_Gp.ViewModel;
using EShop_Gp.General;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.IO;
using System.Threading.Tasks;

namespace EShop_Gp.Controllers
{
    public class PayedController : Controller
    {
        private readonly ApplicationDbContext _Context;

        public PayedController(ApplicationDbContext Context)
        {
            _Context = Context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult _Address()
        {
            var UserN = User.Identity.Name;
            var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN).Id;
            if (UserId != null)
            {
                var UserDetail = _Context.UserData.FirstOrDefault(x => x.UserId == UserId);
                UserDataViewModel UserDataViewModel = new UserDataViewModel();

                if (UserDetail != null)
                {
                    UserDataViewModel.FullName = UserDetail.FullName;
                    UserDataViewModel.BuildingNameOrNum = UserDetail.BuildingNameOrNum;
                    UserDataViewModel.CityAndArea = UserDetail.CityAndArea;
                    UserDataViewModel.NearestToken = UserDetail.NearestToken;
                    UserDataViewModel.PhoneNumber = UserDetail.PhoneNumber;
                    UserDataViewModel.Street = UserDetail.Street;
                 
                    return PartialView(UserDataViewModel);
                }
                else
                {
                    return PartialView(UserDataViewModel);
                }
            }
            else
            {
                return null;
            }
        }
        public IActionResult _Payment()
        {
            return PartialView();
        }
        public IActionResult _GoodsAndShipping()
        {
            var UserN = User.Identity.Name;
            var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN);
            if (UserId != null)
            {
                var viewmodel = new PopUp()
                {
                    carts = _Context.Cart.Include(c => c.Product).Include(c => c.Items).Where(x => x.UserId == UserId.Id && x.IsDeleted == false && x.IsPaid == false).ToList(),
                };
                viewmodel.SumPrice = viewmodel.carts.Select(s => s.Items.Price).Sum();
                viewmodel.Items = _Context.Items.Where(x => x.ProductId == viewmodel.carts.FirstOrDefault().ProductId).Take(3).ToList();
                viewmodel.DayOfReceipt = DateTime.Now.AddDays(5).ToString("yyyy/MM/dd");
                viewmodel.CartIds = viewmodel.carts.Select(x => x.Id).ToList();

                return PartialView(viewmodel);
            }
            else
            {
                var viewmodel = new PopUp()
                {
                    carts = _Context.Cart.Include(c => c.Product).Include(c => c.Items).ToList(),
                };
                var cart = _Context.Items.Where(x => x.AddToCart > 0);
                return PartialView("_LoginToContinueCart", viewmodel);
            }
        }
        public ActionResult AddToCard(string CardNumber, string ExpirationDate, string NameOnTheCard)
        {
            var PayedByVisa = _Context.UserPayment.Where(x => x.CardNumber == CardNumber && x.ExpirationDate == ExpirationDate && x.NameOnTheCard == NameOnTheCard && x.IsVisa == true).FirstOrDefault();
            if (PayedByVisa != null)
            {
                var UserN = User.Identity.Name;
                var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN);
                var Data = _Context.UserData.Where(x => x.UserId == UserId.Id).FirstOrDefault();

                Data.IsCreditCard = true;
                _Context.Entry(Data).CurrentValues.SetValues(Data);
                _Context.SaveChanges();

                return PartialView("_Payment");
            }
            else
            {
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult SaveAddress(UserDataViewModel UserDataV)
        {
            var UserN = User.Identity.Name;
            var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN).Id;
            if (UserId != null)
            {
                var Cart = _Context.Cart.Where(x => x.UserId == UserId).FirstOrDefault();
                var UserDetail = _Context.UserData.FirstOrDefault(x => x.UserId == UserId && x.FullName == UserDataV.FullName && x.PhoneNumber == UserDataV.PhoneNumber && x.Street == UserDataV.Street && x.BuildingNameOrNum == UserDataV.BuildingNameOrNum && x.CityAndArea == UserDataV.CityAndArea && x.NearestToken == UserDataV.NearestToken);

                if (UserDetail != null)
                {
                    return Json("Done");
                }
                else
                {
                    UserData Userdata = new UserData();
                    Userdata.FullName = UserDataV.FullName;
                    Userdata.PhoneNumber = UserDataV.PhoneNumber;
                    Userdata.Street = UserDataV.Street;
                    Userdata.BuildingNameOrNum = UserDataV.BuildingNameOrNum;
                    Userdata.CityAndArea = UserDataV.CityAndArea;
                    Userdata.NearestToken = UserDataV.NearestToken;
                    Userdata.UserId = UserId;
                    Userdata.CartId = Cart.Id;

                    _Context.UserData.Add(Userdata);
                    _Context.SaveChanges();
                    return Json("Done");
                }
            }
            else
            {
                return Json("Error");
            }
        }

        public ActionResult FinallyPaid(bool Cash)
        {
            if (Cash == true)
            {
                var UserN = User.Identity.Name;
                var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN);
                var Data = _Context.UserData.Where(x => x.UserId == UserId.Id).FirstOrDefault();

                Data.IsCash = true;

                _Context.Entry(Data).CurrentValues.SetValues(Data);
                _Context.SaveChanges();
                return Json("CashDone");
            }
            else
            {
                var UserN = User.Identity.Name;
                var UserId = _Context.Users.FirstOrDefault(x => x.UserName == UserN);
                var Data = _Context.UserData.Where(x => x.UserId == UserId.Id).FirstOrDefault();
                if (Data.IsCreditCard == true)
                {
                    return Json("CreditDone");
                }
                else
                {
                    return Json("ChoosePaymentMethod");
                }
            }
        }
        public ActionResult ConfirmOrder(int CartMasterId)
        {
            try
            {
                var CartMaster = _Context.CartMaster.FirstOrDefault(x => x.Id == CartMasterId);
                CartMaster.IsPaid = true;

                _Context.Entry(CartMaster).CurrentValues.SetValues(CartMaster);
                _Context.SaveChanges();
                var CartDetail = _Context.Cart.Where(x => x.CartMasterId == CartMaster.Id).ToList();

                foreach (var item in CartDetail)
                {
                    var CartModel = _Context.Cart.FirstOrDefault(x => x.Id == item.Id);
                    CartModel.IsPaid = true;

                    _Context.Entry(CartModel).CurrentValues.SetValues(CartModel);
                }
                _Context.SaveChanges();

                return RedirectToAction("Index","Home");
            }
            catch (Exception)
            {
                throw;
            }
        }

    }
}

EShop-Gp/Views/Cart/Index.cshtml
@model EShop_Gp.ViewModel.PopUp

@{
    ViewBag.Title = "My Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .plus-minus-input {
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
    }

        .plus-minus-input .input-group-field {
            text-align: center;
            margin-left: 0.5rem;
            margin-right: 0.5rem;
            padding: 1rem;
        }

            .plus-minus-input .input-group-field::-webkit-inner-spin-button,
            .plus-minus-input .input-group-field ::-webkit-outer-spin-button {
                -webkit-appearance: none;
                appearance: none;
            }

        .plus-minus-input .input-group-button .circle {
            border-radius: 50%;
            padding: 0.25em 0.8em;
        }
</style>
@{
    int Count = 1;
}
@if (Model != null)
{
    <div class="row">
        <div class="col-lg-3">
            <div class="position-sticky">
                <div class="p-4 mb-5 bg-light">
                    <h1 class="mb-0">
                        المجموع الكلي :
                        @Model.SumPrice
                    </h1>
                    <a onclick="location.href='@Url.Action("Index", "Payed")'"><button class="px-lg-5 col-xl-9 bg-primary alert-success">تابع عملية الشراء</button></a>
                </div>
            </div>
            <div class="py-xl-5 bg-light panel-heading text-center">
                @if (Model.Items != null)
                {
                    <h4 class="fst-italic text-center">قد يعجبك أيضًا</h4>
                    @foreach (var item in Model.Items)
                    {
                        if (Count <= 3)
                        {
                            <div class="list-unstyled mb-4">
                                <img class="pic-1" src="@Url.Content(item.Image)" style="width:100px">
                                <p class="title">@item.NameAr</p>
                                <div class="price">
                                    @item.Price
                                </div>
                                <a onclick="location.href='@Url.Action("AddToCart", "Home" , new {id =item.Id , ProductId = item.ProductId})'"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                            Count++;
                        }
                    }
                }
                else
                {
                }

            </div>
        </div>

        <div class="col-lg-9" id="CartTable">

        </div>

    </div>

}
else
{
}

<script>
    $(document).ready(function () {
        debugger;
        $.ajax({
            url: '@Url.Action("_Cart", "Cart")',
            data: {},
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                debugger;
                $("#CartTable").html('');
                $("#CartTable").html(data);
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) { }
        });

    });

</script>

EShop-Gp/Views/Cart/_Cart.cshtml
@model EShop_Gp.ViewModel.PopUp

@{
    ViewBag.Title = "My Cart";
}

@{
    int row = 1;
}


<div id="CartTable">
    @if (Model.carts != null)
    {
        <h1 class="fst-italic text-lg-right">عربة التسوق</h1>
        <hr />
        @foreach (var item in Model.carts)
        {
            <h1 class="text-lg-left">السعر : @item.Items.Price</h1>

            <div class="row" id="@row" data-rowid="@row">
                <div class="col-lg-10 text-lg-right">
                    <h4>@item.Items.NameAr</h4>
                    <p>مؤهل للحصول على شحن مجاني</p>
                </div>
                <a><img onclick="DeleteDiscarding(@item.Items.Id)" class="svg-icon" src="~/Image/018-delete.svg" title="delete" style="width: 6%;" /> </a>
                <div class="col-lg-2 text-lg-right">
                    <img class="pic-1" src="@Url.Content(item.Items.Image)" style="width:100px">
                </div>
            </div>
            <hr />
        }
    }
    else
    {
        <h1 class="fst-italic text-lg-right">العربة فارغة</h1>
    }


</div>


<script>
    function DeleteDiscarding(id) {
         debugger;
             $.ajax({
                 url: '@Url.Action("DeleteDiscarding", "Cart")',
                 data: { Id: id },
                 contentType: 'application/json; charset=utf-8',
                 success: function (data) {
                     debugger;
                     $("#CartTable").html('');
                     $("#CartTable").html(data);
                 },
                 error: function (XMLHttpRequest, textStatus, errorThrown) { }
             });
       };

</script>

EShop-Gp/Views/Cart/_LoginToContinueCart.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="caption" style="text-align:center">
                            <h1 class="fst-italic text-lg-right">برجاء تسجيل الدخول لاتمام العملية</h1>
                            <hr />
                            <i><a style="background-color: #ffffff; color: #000000;" href="~/Register/Register" class="btn btn-primary">اشترك الان</a></i>
                            <i><a style="background-color: #ffe450; color: #000000;" href="~/Login/Login" class="btn btn-light">تسجيل الدخول الي حسابك</a></i>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

EShop-Gp/Views/Cart/_StatusOrder.cshtml
@model List<EShop_Gp.ViewModel.StatusOrderViewModel>

@{
    ViewBag.Title = "My Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model != null)
{
    <div class="container-fluid padding">
        <div class="row padding">
            @foreach (var item in Model)
            {
                <div class="col-md-3 col-sm-6">
                    <div class="product-grid3">
                        <div class="product-image3">
                            <img class="card-title" style="width: 100%;" src="@Url.Content(item.Image)" alt="...">
                            <h4 class="card-title"><b>@item.NameAr</b></h4>
                            @*<h4 class="card-title"><b>@item.NameEn</b></h4>*@
                            <p class="card-text">@item.Price</p>
                            <p class="card-text">@item.OrderTimeOfReceipt</p>

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <div class="container ">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="caption" style="text-align:center">
                                <h1 class="fst-italic text-lg-center">لا توجد اي طلبات معلقة</h1>
                                <hr />
                                <i><a style="background-color: #ffe450; color: #000000;" href="~/Home/Index" class="btn btn-light">اذهب للتسوق</a></i>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

}